Add `model_to_solution` and `model_to_state`.
Jij-Inc/ommx pull request #145
Opened 2024-11-18 07:37 UTC by NY57

# 変更点
- 変更前の時点では、`model_to_solution` 関数が`ommx.v1.State`を返している状態だったため、関数名を`model_to_state`に変更しました
- `ommx.v1.Solution`を返す関数`model_to_solution`を新しく実装しました
- この変更に伴い、`solve`関数の内部処理を新規実装した`model_to_solution`に置き換えました

# 注意事項
`model_to_solution`関数の破壊的変更のため、最低でもマイナーバーションを上げる必要があります。

2024-11-18 07:59 UTC, termoshtt commented on python/ommx-python-mip-adapter/ommx_python_mip_adapter/ommx_to_python_mip.py
>          >>> ommx_solutions.entries
```suggestion
        >>> state = adapter.model_to_state(model, ommx_instance)
        >>> state.entries
```

2024-11-18 07:59 UTC, termoshtt commented on python/ommx-python-mip-adapter/ommx_python_mip_adapter/python_mip_to_ommx.py
>          >>> ommx_solutions.entries
```suggestion
        >>> state = adapter.model_to_state(model, ommx_instance)
        >>> state.entries
```

2024-11-18 07:59 UTC, termoshtt commented on python/ommx-python-mip-adapter/ommx_python_mip_adapter/python_mip_to_ommx.py
> +        >>> from ommx.v1.solution_pb2 import Optimality
```suggestion
```

この行は要らないはず

2024-11-18 07:59 UTC, termoshtt commented on python/ommx-python-mip-adapter/README.md
>  print(ommx_solutions)
```suggestion
state = adapter.model_to_state(model, ommx_instance)

print(state)
```

2024-11-18 07:59 UTC, termoshtt commented on python/ommx-python-mip-adapter/tests/test_integration.py
> +    ommx_solution = adapter.model_to_state(model, ommx_instance_bytes)
ここも変数名 `state` にしましょう

2024-11-19 01:24 UTC, Shitaro approved these changes
I believe there is no need to add `model_to_state` as a separate function for the following reasons:

- The `state` field of `ommx.v1.Solution` already contains `ommx.v1.State`.   
- To my knowledge, there is no use case that requires retrieving only `ommx.v1.State`.

However, the implementation of model_to_solution will use model_to_state. It would not be desirable to pay the cost of making it private.

For these reasons, I believe the current approach in this PR is appropriate.

2024-11-19 02:50 UTC, termoshtt commented
> To my knowledge, there is no use case that requires retrieving only ommx.v1.State.

Since evaluating into `ommx.v1.Solution` is somewhat heavy, it would be better to use `State` instead of `Soluiton` when Python-MIP adapter is used as a component of higher level algorithm. Basically `State` is for computer and `Solution` is for person.

2024-11-19 03:08 UTC, Shitaro commented
> > To my knowledge, there is no use case that requires retrieving only ommx.v1.State.
> 
> Since evaluating into `ommx.v1.Solution` is somewhat heavy, it would be better to use `State` instead of `Soluiton` when Python-MIP adapter is used as a component of higher level algorithm. Basically `State` is for computer and `Solution` is for person.

In fact, as you mentioned, from a computational point of view, if just getting the state is sufficient, then it's better to just return the state without any further computation. However, I personally can't think of a situation where you would use just the state without the solution when implementing advanced algorithms. Wouldn't you generally need not only the intermediate solution but also the associated optimal value when implementing algorithms? For example, in a simple example like branch-and-bound, we would use both the solution of the relaxed subproblem (according to `State`) and its optimal value.
Well, it's quite possible that I simply can't imagine such use cases due to my limited experience and knowledge of mathematical optimisation.

In any case, I have no intention of opposing the addition of a function that returns `State`.

2024-11-19 03:12 UTC, Shitaro requested changes
As this PR introduces breaking changes, could you please update the minor version to 1.4.0?

2024-11-19 05:05 UTC, termoshtt approved these changes
LGTM

2024-11-19 05:28 UTC, merged