QPLIB format parser
Jij-Inc/ommx pull request #250
Opened 2024-12-24 01:46 UTC by Zengor

2025-01-10 08:18 UTC, termoshtt requested changes

2025-01-10 08:18 UTC, termoshtt commented on rust/ommx/src/qplib.rs
> +    },
It would be better to convert `WithLine` as `ParseError` type, and other entries as separated enum, e.g. `ParseErrorReason`.

2025-01-10 08:18 UTC, termoshtt commented on rust/ommx/src/qplib.rs
> +    Io(#[from] std::io::Error),
IO error is not a parse error. Since `std::io::Error` does not contains which file is tried to opened, returning this error is not user-friendly. We should rather return `anyhow::Result` from function which may returns IO error with `anyhow::Context` to tell which file is opened.

For the actual parse errors like invalid var types, creating this `ParseError` and returned within `anyhow::Error`. Users can get the error as  `ParseError` via `downcast` https://docs.rs/anyhow/latest/anyhow/struct.Error.html#method.downcast

2025-01-10 08:18 UTC, termoshtt commented on rust/ommx/src/qplib/convert.rs
Similar to MPS, we want to create some cases which is invariant via the round-trip ommx.v1.Instance -> QPLIB format -> ommx.v1.Instance. Do you have any idea especially for ID mapping.

2025-01-20 23:09 UTC, Zengor commented on rust/ommx/src/qplib/convert.rs
I've been thinking about it and there are a few ways but also some unresolved issues.

The biggest problem is that the QPLIB is meant to reduce the number of constraints by allowing two-sided `c_l <= expr <= c_r` inequalities, and so to have shorter QPLIB files we'd need to add special handling for that when outputting. On the other hand that would be pretty annoying to implement as the expressions wouldn't be equal in OMMX (one of them would be multiplied by -1). It'd be simpler for our implementation to ignore this and just double up on constraints when necessary, especially if what we care about is mostly the stability of IDs.

The other big problem is just the fact that OMMX IDs don't need to be contiguous, while QPLIB format IDs do have that assumption (as it just lists the number of variables/constraints at the top and assumes they will be numbered 1..N and 1..M)

When the IDs in the OMMX instance are sequential _and_ starting from 1, we could just have a 1:1 correspondence between the file IDs and the instance IDs. We'd still need a metadata marker so the parser knows to recover IDs for constraints (as opposed to the current way the parser handles splitting constraint IDs). But this would always have to be just a special case if we choose to add this capability.

For the more general case, the QPLIB file does still allow metadata like variable/constraint names, which we can use to have a very similar setup to our MPS ID mapping: just give them special names that contains their OMMX IDs, while the IDs in the file are fully sequential and not required to follow the OMMX instance. This is probably the simplest to implement.

2025-01-23 12:40 UTC, termoshtt commented on rust/ommx/src/qplib/convert.rs
Great, it makes the problem clear.

It looks unrealistic to create a direct mapping from OMMX ID to QPLIB ID as you say. It would be better to use metadata to keep tracking the information of OMMX side in QPLIB format.

Anyway, this will be an issue after implementing QPLIB output. I will merge this PR as it is. Thanks a lot!

2025-01-23 12:41 UTC, merged